TRAIN_PATH="Dataset"
PREDICTION_FOLDER_PATH="Predict_img"
CALLBACKS_PATH="Sign_Lenguage_callbacks.pth.tar"

VALID_SPLIT=0.2
TEST_SPLIT=0.1
RESHAPE_IMG_SIZE=128
CHANNEL_SIZE=1

BATCH_SIZE=100
EPOCHS=6
LEARNING_RATE=0.001

TRAIN_MODEL=False
TEST_MODEL=False
VISUALIZATION=False
LOADING_CHECKPOINT=True
PREDICT=True

